name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    - name: Login to ECR
      run: |
        aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin YOUR_ECR_URI

    - name: Build Docker Image
      run: docker build -t aws-devops-project .

    - name: Tag Image
      run: docker tag aws-devops-project:latest 019922908229.dkr.ecr.eu-north-1.amazonaws.com/aws-devops-project:latest

    - name: Push Image
      run: docker push 019922908229.dkr.ecr.eu-north-1.amazonaws.com/aws-devops-project:latest
